title: Dez
email: dez@airmail.cc
description: > # this means to ignore newlines until "baseurl:"
  This is my new website

# social links
twitter_username: @nathanmanzoo

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
